export const ACCOUNT_REQUEST = "ACCOUNT_REQUEST";
export const ACCOUNT_FAILURE = "ACCOUNT_FAILURE";
export const ACCOUNT_CREATE = "ACCOUNT_CREATE";
export const ACCOUNT_GET_DETAIL = "ACCOUNT_GET_DETAIL";
export const ACCOUNT_GET_ALL = "ACCOUNT_GET_ALL";