export const TRANSACTION_REQUEST = "TRANSACTION_REQUEST";
export const TRANSACTION_FAILURE = "TRANSACTION_FAILURE";
export const TRANSACTION_CREATE = "TRANSACTION_CREATE";
export const TRANSACTION_GET_DETAIL = "TRANSACTION_GET_DETAIL";
export const TRANSACTION_GET_LIST = "TRANSACTION_GET_LIST";
export const TRANSACTION_GET_ALL = "TRANSACTION_GET_ALL";